# Generated by Django 5.2.2 on 2025-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='password2',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
