# Generated by Django 5.2.2 on 2025-06-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_user_details_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='Email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='Mobile_No',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='Name',
            new_name='username',
        ),
    ]
