# Generated by Django 5.2.2 on 2025-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_orders_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_detail',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
